version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8501:8501"
    working_dir: /code/src
    command: streamlit run gui.py --server.port=8501 --logger.level=debug #sh run.sh 
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always

